spring.data.mongodb.uri=mongodb+srv://oddlyadmin:oddly123@oddly.cgzw1ep.mongodb.net/oddly?retryWrites=true&w=majority&appName=oddly
spring.application.name=oddly-backend
server.port=8080
jwt.secret=oddly-super-secret-key-change-this-in-production-make-it-long
jwt.expiration=86400000
groq.api.key=gsk_4RT79Sk9P1qkFT05h8hyWGdyb3FYYLUJAjl9qUWkL6F7xvZuGmmjgsk_hX1qSlPhjvKNNsByLVYnWGdyb3FYaHoZwwfhxRgbjt0FXfsiAVcv
groq.api.url=https://api.groq.com/openai/v1/chat/completions
groq.model=llama-3.3-70b-versatile
spring.mvc.pathmatch.use-suffix-pattern=false
lastfm.api.key=7f00ca9157bcd3c2abd4d9201e58a4f4
omdb.api.key=14b6ea64