spring.application.name=oddly-backend
spring.data.mongodb.uri=mongodb+srv://oddlyadmin:oddly123@oddly.cgzw1ep.mongodb.net/oddly?retryWrites=true&w=majority&appName=oddly
jwt.secret=oddly_super_secret_key_2026_make_it_long
jwt.expiration=86400000
groq.api.key=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
groq.api.url=https://api.groq.com/openai/v1/chat/completions
groq.model=llama-3.3-70b-versatile
lastfm.api.key=7f00ca9157bcd3c2abd4d9201e58a4f4
omdb.api.key=14b6ea64
server.port=8080